//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessManagerConsoleClient.ProcessManager {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProcessManager.IProcessManager")]
    public interface IProcessManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessManager/GetProcess", ReplyAction="http://tempuri.org/IProcessManager/GetProcessResponse")]
        string[] GetProcess(string Login, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProcessManager/GetProcess", ReplyAction="http://tempuri.org/IProcessManager/GetProcessResponse")]
        System.Threading.Tasks.Task<string[]> GetProcessAsync(string Login, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProcessManagerChannel : ProcessManagerConsoleClient.ProcessManager.IProcessManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcessManagerClient : System.ServiceModel.ClientBase<ProcessManagerConsoleClient.ProcessManager.IProcessManager>, ProcessManagerConsoleClient.ProcessManager.IProcessManager {
        
        public ProcessManagerClient() {
        }
        
        public ProcessManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcessManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcessManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetProcess(string Login, string Password) {
            return base.Channel.GetProcess(Login, Password);
        }
        
        public System.Threading.Tasks.Task<string[]> GetProcessAsync(string Login, string Password) {
            return base.Channel.GetProcessAsync(Login, Password);
        }
    }
}
